apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Add any, it is EFS